use_frameworks!

target 'ZZScanQR_Example' do
  pod 'ZZScanQR', :path => '../'

  target 'ZZScanQR_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
